spring.application.name=MJCinema
# Datasource
spring.datasource.url=mysql://root:oXByXEaulowIZtaxZJbXLONnVOzAzRte@ballast.proxy.rlwy.net:47195/mjcinema
#Database Access
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
spring.jpa.properties.hibernate.format_sql=true

#TMDB Access
tmdb.api.key=${TMDB_API_KEY}
tmdb.base.url=${TMDB_BASE_URL}

#PORT
server.port=${PORT:8080}
server.address=0.0.0.0
